### ISSUE TITLE
App crashing1

### ISSUE THREAD

**Issue by JunWei96** [testathor/pe-results#1]
# Description
- [ ] test
# Team's Response
test
 ## State the duplicated issue here, if any
--

**Comment by testathorStudent** [comment]
Duplicate of #12
wqe

**Comment by testathorStudent** [comment]
## Team's Response
test
## State the duplicated issue here, if any
Duplicate of #71

**Comment by testathorStudent** [comment]
## Team's Response
test
## State the duplicated issue here, if any
Duplicate of #

**Comment by testathorStudent** [comment]
## Team's Response
aaaa









## State the duplicated issue here, if any
Duplicate of #71
